# About the project

*Write a short description about the course and add a link to your GitHub repository here. This is an R Markdown (.Rmd) file so you should use R Markdown syntax.*

# Week 1

```{r}
# This is a so-called "R chunk" where you can write R code.

date()

```

I'm taking this course very close to what is (hopefully) the end of my doctoral studies, honestly mainly to collect some of the remaining credits that I need.

That said, the course does contain some interesting and potentially useful topics. I have familiarity with R, RStudio, R Notebooks, GitHub and so forth, but have just learned things as I've needed them and have never put any effort into actually studying things. I suppose I can learn a thing or two about how to properly use these tools; and similarly for all the analysis techniques that are included in the course syllabus. 

I have a bit of a love-hate relationship with R; I used to be a Python coder, but at some point realized that I've ended up working mostly with R. I'm familiar enough with it that the first few chapters of the RHDS book seemed to mainly contain stuff that I already know.

I find it curious, actually, that the book teaches the tidyverse package from the very beginning. The fact that there's an entire 'sub-language' within R, in the form of tidyverse, is one of the things that I really don't enjoy that much. I like tidyverse, but things get confusing when tidyverse and base-R are mixed up (as they inevitably are, at times). But I guess this shows that tidyverse is the way to go in the future, and this is good to know.

Here's the [link](https://github.com/aasitus/IODS-project) to my GitHub repo.

